name: Build-linux
on:
  push:
    branches: [ EB-System ]
  pull_request:
    branches: [ EB-System ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make run -C 3_Implementation
